//
//  IllustrationService+RegionalPlates.swift
//  Fieldnote
//
//  GENERATED — do not edit by hand. Produced by
//  backend/fixtures/integrate_plates.py from the public-domain plates sourced for
//  region-pack taxa (see Docs/RegionalizedCatalogPlan.md, IllustrationSourcing.md).
//
//  Regional plates are keyed by scientific name (genus_species, lowercase,
//  underscore). Each asset lives in Assets.xcassets/Illustrations/ and carries a
//  public-domain credit. 97 plates.
//

import Foundation

extension IllustrationService {
    /// Asset names for regional public-domain plates (== scientific name key).
    static let regionalPlateAssets: Set<String> = [
        "adenostoma_fasciculatum",
        "ambrosia_trifida",
        "aquilegia_coerulea",
        "arbutus_menziesii",
        "artemisia_vulgaris",
        "asclepias_speciosa",
        "asystasia_gangetica",
        "berberis_aquifolium",
        "berberis_nervosa",
        "berberis_trifoliolata",
        "callicarpa_americana",
        "calochortus_gunnisonii",
        "carnegiea_gigantea",
        "casuarina_equisetifolia",
        "celastrus_orbiculatus",
        "chamaenerion_angustifolium",
        "chimaphila_maculata",
        "claytonia_sibirica",
        "clusia_rosea",
        "cochemiea_grahamii",
        "commelina_erecta",
        "cylindropuntia_acanthocarpa",
        "cylindropuntia_bigelovii",
        "cylindropuntia_echinocarpa",
        "cylindropuntia_imbricata",
        "cypripedium_acaule",
        "cytisus_scoparius",
        "dicranopteris_linearis",
        "dipterostemon_capitatus",
        "dodonaea_viscosa",
        "drosera_capillaris",
        "echinocereus_engelmannii",
        "echinocereus_triglochidiatus",
        "erythrina_herbacea",
        "erythronium_americanum",
        "eschscholzia_californica",
        "fagus_grandifolia",
        "ferocactus_cylindraceus",
        "fouquieria_splendens",
        "frasera_speciosa",
        "gaultheria_shallon",
        "geranium_robertianum",
        "glechoma_hederacea",
        "heteromeles_arbutifolia",
        "hibiscus_tiliaceus",
        "holodiscus_discolor",
        "ilex_vomitoria",
        "ipomopsis_aggregata",
        "juniperus_ashei",
        "lamium_amplexicaule",
        "larrea_tridentata",
        "liquidambar_styraciflua",
        "lyonia_lucida",
        "malosma_laurina",
        "melilotus_officinalis",
        "miconia_crenata",
        "mitchella_repens",
        "momordica_charantia",
        "morinda_citrifolia",
        "neltuma_glandulosa",
        "oenothera_speciosa",
        "onoclea_sensibilis",
        "opuntia_basilaris",
        "opuntia_polyacantha",
        "oxalis_pes-caprae",
        "parkinsonia_microphylla",
        "pediocactus_simpsonii",
        "phytolacca_americana",
        "pinus_ponderosa",
        "pinus_scopulorum",
        "pinus_strobus",
        "polystichum_acrostichoides",
        "populus_tremuloides",
        "prunella_vulgaris",
        "pseudotsuga_menziesii",
        "quercus_agrifolia",
        "quercus_gambelii",
        "rhus_copallina",
        "rhus_integrifolia",
        "rosa_multiflora",
        "rubus_spectabilis",
        "rubus_ursinus",
        "sabal_palmetto",
        "sambucus_canadensis",
        "sambucus_racemosa",
        "scaevola_taccada",
        "serenoa_repens",
        "solanum_dulcamara",
        "sphaeralcea_coccinea",
        "symphoricarpos_albus",
        "symplocarpus_foetidus",
        "thespesia_populnea",
        "thuja_plicata",
        "toxicodendron_radicans",
        "umbellularia_californica",
        "urena_lobata",
        "vitis_rotundifolia"
    ]

    /// Attribution for each regional plate, keyed by asset name.
    static let regionalPlateCredits: [String: IllustrationCredit] = [
        "adenostoma_fasciculatum": IllustrationCredit(creator: "Unknown", title: "Grease-wood adenostoma fasciculatum 6 feet high", year: 1911, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Grease-wood_adenostoma_fasciculatum_6_feet_high.jpg"), license: .publicDomain),
        "ambrosia_trifida": IllustrationCredit(creator: "NRCS National Wetland Team, Fort Worth, TX.", title: "Ambrosia trifida-linedrawing", year: 2008, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Ambrosia_trifida-linedrawing.png"), license: .publicDomain),
        "aquilegia_coerulea": IllustrationCredit(creator: "O.V Kirkton", title: "Aquilegia coerulea - Kirkton 1909", year: 1909, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Aquilegia_coerulea_-_Kirkton_1909.png"), license: .publicDomain),
        "arbutus_menziesii": IllustrationCredit(creator: "M.S. del., J.N.Fitch lith.", title: "Arbutus menziesii 135-8249", year: 1909, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Arbutus_menziesii_135-8249.jpg"), license: .publicDomain),
        "artemisia_vulgaris": IllustrationCredit(creator: "Köhler, Franz Eugen; Müller, Walther; Vogtherr, Max; Gürke, M;", title: "Artemisia vulgaris - Köhlers Medizinalpflanzen, Band 3, 1898, 0399 clean", year: 1898, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Artemisia_vulgaris_-_K%C3%B6hlers_Medizinalpflanzen,_Band_3,_1898,_0399_clean.jpg"), license: .publicDomain),
        "asclepias_speciosa": IllustrationCredit(creator: "USDA Natural Resources Conservation Service.", title: "Asclepias speciosa-illustration", year: 2008, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Asclepias_speciosa-illustration.png"), license: .publicDomain),
        "asystasia_gangetica": IllustrationCredit(creator: "art: Govindoo; text:Robert Wight", title: "Asystasia gangetica Govindoo", year: 1854, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Asystasia_gangetica_Govindoo.jpg"), license: .publicDomain),
        "berberis_aquifolium": IllustrationCredit(creator: "Unknown", title: "PSM V45 D620 Berberis aquifolium", year: 1894, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:PSM_V45_D620_Berberis_aquifolium.jpg"), license: .publicDomain),
        "berberis_nervosa": IllustrationCredit(creator: "Frederick Traugott Pursh", title: "Flora Americae Septentrionalis - or, A systematic arrangement and description of the plants of North America. Containing", year: 1816, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Flora_Americae_Septentrionalis_-_or,_A_systematic_arrangement_and_description_of_the_plants_of_North_America._Containing,_besides_what_have_been_described_by_preceding_authors,_many_new_and_rare_(14760837191).jpg"), license: .publicDomain),
        "berberis_trifoliolata": IllustrationCredit(creator: "Van Houtte, Louis", title: "Flore des serres et des jardins de l'Europe (7972574652)", year: 1845, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Flore_des_serres_et_des_jardins_de_l%27Europe_(7972574652).jpg"), license: .publicDomain),
        "callicarpa_americana": IllustrationCredit(creator: "Mary Vaux Walcott", title: "Beauty Berry (Callicarpa americana)", year: 1923, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Beauty_Berry_(Callicarpa_americana)_by_Mary_Vaux_Walcott-saam1970.355.548.jpg"), license: .cc0),
        "calochortus_gunnisonii": IllustrationCredit(creator: "Internet Archive Book Images", title: "Rocky Mountain flowers - an illustrated guide for plant-lovers and plant-users (1920) (14781816251)", year: 1920, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Rocky_Mountain_flowers_-_an_illustrated_guide_for_plant-lovers_and_plant-users_(1920)_(14781816251).jpg"), license: .publicDomain),
        "carnegiea_gigantea": IllustrationCredit(creator: "Joseph T. Rothrock", title: "Carnegiea gigantea Frontispiece US Geographical Surveys VI Botany 1878", year: 1878, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Carnegiea_gigantea_Frontispiece_US_Geographical_Surveys_VI_Botany_1878.jpg"), license: .publicDomain),
        "casuarina_equisetifolia": IllustrationCredit(creator: "Megustanlasframbuesas", title: "Casuarina equisetifolia BYN", year: 2020, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Casuarina_equisetifolia_BYN.jpg"), license: .cc0),
        "celastrus_orbiculatus": IllustrationCredit(creator: "New York Botanical Garden", title: "Addisonia - colored illustrations and popular descriptions of plants (1916-(1964)) (16771683392)", year: 2015, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Addisonia_-_colored_illustrations_and_popular_descriptions_of_plants_(1916-(1964))_(16771683392).jpg"), license: .publicDomain),
        "chamaenerion_angustifolium": IllustrationCredit(creator: "Unknown", title: "Dutch: Smal blaadige bastaard Wederik Plate 0007, Flora Batava (KB), volume 1title QS:P1476,nl:\"Smal blaadige bastaard W", year: 2023, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Epilobium_angustifolium_(modern%3DChamaenerion_angustifolium)_-_Pl0007_-_FloraBatava-KB-v01.jpg"), license: .publicDomain),
        "chimaphila_maculata": IllustrationCredit(creator: "Internet Archive Book Images", title: "Meehans' monthly - a magazine of horticulture, botany and kindred subjects (1899) (14782973142)", year: 1899, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Meehans%27_monthly_-_a_magazine_of_horticulture,_botany_and_kindred_subjects_(1899)_(14782973142).jpg"), license: .publicDomain),
        "claytonia_sibirica": IllustrationCredit(creator: "Kungl. Svenska vetenskapsakademien", title: "Svenska vetenskapsakademien handlingar (1906) (14760208916)", year: 1906, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Svenska_vetenskapsakademien_handlingar_(1906)_(14760208916).jpg"), license: .publicDomain),
        "clusia_rosea": IllustrationCredit(creator: "Pierre-Joseph Buc'hoz", title: "Herbier Colorie de l'Amerique (30906819557)", year: 1783, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Herbier_Colorie_de_l%27Amerique_(30906819557).jpg"), license: .publicDomain),
        "cochemiea_grahamii": IllustrationCredit(creator: "Engelmann, George, 1809-1884; Shaw, Henry, 1800-1889; Trelease, William, 1857-1945; Gray, Asa, 1810-1888", title: "The botanical works of the late George Engelmann, collected for Henry Shaw, esq (1887) (20375999236)", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_botanical_works_of_the_late_George_Engelmann,_collected_for_Henry_Shaw,_esq_(1887)_(20375999236).jpg"), license: .publicDomain),
        "commelina_erecta": IllustrationCredit(creator: "Britton, N.L., and A. Brown", title: "Commelina erecta 001 pvd", year: 1913, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Commelina_erecta_001_pvd.jpg"), license: .publicDomain),
        "cylindropuntia_acanthocarpa": IllustrationCredit(creator: "Engelmann, George, 1809-1884; Shaw, Henry, 1800-1889; Trelease, William, 1857-1945; Gray, Asa, 1810-1888", title: "The botanical works of the late George Engelmann, collected for Henry Shaw, esq (1887) (20215902859)", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_botanical_works_of_the_late_George_Engelmann,_collected_for_Henry_Shaw,_esq_(1887)_(20215902859).jpg"), license: .publicDomain),
        "cylindropuntia_bigelovii": IllustrationCredit(creator: "United States. War Dept; Henry, Joseph, 1797-1878; Baird, Spencer Fullerton, 1823-1887; United States. Army. Corps of Engineers", title: "Reports of explorations and surveys, to ascertain the most practicable and economical route for a railroad from the Miss", year: 1855, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Reports_of_explorations_and_surveys,_to_ascertain_the_most_practicable_and_economical_route_for_a_railroad_from_the_Mississippi_River_to_the_Pacific_Ocean_(1855)_(14758559565).jpg"), license: .publicDomain),
        "cylindropuntia_echinocarpa": IllustrationCredit(creator: "Engelmann, George, 1809-1884; Shaw, Henry, 1800-1889; Trelease, William, 1857-1945; Gray, Asa, 1810-1888", title: "The botanical works of the late George Engelmann, collected for Henry Shaw, esq (1887) (20215902859)", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_botanical_works_of_the_late_George_Engelmann,_collected_for_Henry_Shaw,_esq_(1887)_(20215902859).jpg"), license: .publicDomain),
        "cylindropuntia_imbricata": IllustrationCredit(creator: "Engelmann, George, 1809-1884; Shaw, Henry, 1800-1889; Trelease, William, 1857-1945; Gray, Asa, 1810-1888", title: "The botanical works of the late George Engelmann, collected for Henry Shaw, esq (1887) (20215902859)", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_botanical_works_of_the_late_George_Engelmann,_collected_for_Henry_Shaw,_esq_(1887)_(20215902859).jpg"), license: .publicDomain),
        "cypripedium_acaule": IllustrationCredit(creator: "AnonymousUnknown author [illustrator not stated, no signature]", title: "The American Flora. Vol. 3, 1855 - pl. 15 Cypripedium acaule, Calochortus luteus (10172240515)", year: 1855, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_American_Flora._Vol._3,_1855_-_pl._15_Cypripedium_acaule,_Calochortus_luteus_(10172240515).jpg"), license: .publicDomain),
        "cytisus_scoparius": IllustrationCredit(creator: "Unknown", title: "Illustration Cytisus scoparius0", year: 2004, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Illustration_Cytisus_scoparius0.jpg"), license: .publicDomain),
        "dicranopteris_linearis": IllustrationCredit(creator: "Brackenridge, William D. (William Dunlop), 1810-1893; United States. Dept. of State. Library, former owner. DSI", title: "Botany. Cryptogamia. Filices, including Lycopodiaceae and Hydropterides (1854) (19785747523)", year: 1854, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Botany._Cryptogamia._Filices,_including_Lycopodiaceae_and_Hydropterides_(1854)_(19785747523).jpg"), license: .publicDomain),
        "dipterostemon_capitatus": IllustrationCredit(creator: "Thayer, Emma (Homan)", title: "Wild flowers of the Pacific coast (Plate 8) BHL19082736", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Wild_flowers_of_the_Pacific_coast_(Plate_8)_BHL19082736.jpg"), license: .publicDomain),
        "dodonaea_viscosa": IllustrationCredit(creator: "Rosa Fiveash", title: "Dodonaea viscosa by Rosa Fiveash", year: 1890, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Dodonaea_viscosa_by_Rosa_Fiveash.jpg"), license: .publicDomain),
        "drosera_capillaris": IllustrationCredit(creator: "Petr Dlouhý", title: "Drosera capillaris inflorescence", year: 2009, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Drosera_capillaris_inflorescence.JPG"), license: .publicDomain),
        "echinocereus_engelmannii": IllustrationCredit(creator: "Engelmann, George, 1809-1884; Shaw, Henry, 1800-1889; Trelease, William, 1857-1945; Gray, Asa, 1810-1888", title: "The botanical works of the late George Engelmann, collected for Henry Shaw, esq (1887) (20214444890)", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_botanical_works_of_the_late_George_Engelmann,_collected_for_Henry_Shaw,_esq_(1887)_(20214444890).jpg"), license: .publicDomain),
        "echinocereus_triglochidiatus": IllustrationCredit(creator: "Engelmann, George, 1809-1884; Shaw, Henry, 1800-1889; Trelease, William, 1857-1945; Gray, Asa, 1810-1888", title: "The botanical works of the late George Engelmann, collected for Henry Shaw, esq (1887) (20214444890)", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_botanical_works_of_the_late_George_Engelmann,_collected_for_Henry_Shaw,_esq_(1887)_(20214444890).jpg"), license: .publicDomain),
        "erythrina_herbacea": IllustrationCredit(creator: "Bentham-Moxon Trust.; Curtis, William; Curtis's botanical magazine dedications, 1827-1927 : portraits and biographical notes.; Royal Botanic Gardens, Kew.; Stanley Smith Horticultural Trust.", title: "Curtis's botanical magazine (No. 877) (8469933209)", year: 1805, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Curtis%27s_botanical_magazine_(No._877)_(8469933209).jpg"), license: .publicDomain),
        "erythronium_americanum": IllustrationCredit(creator: "Internet Archive Book Images", title: "American medical botany- being a collection of the native medicinal plants of the United States, containing their botani", year: 1817, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:American_medical_botany-_being_a_collection_of_the_native_medicinal_plants_of_the_United_States,_containing_their_botanical_history_and_chemical_analysis,_and_properties_and_uses_in_medicine,_diet_and_(14740719936).jpg"), license: .publicDomain),
        "eschscholzia_californica": IllustrationCredit(creator: "Edward Step &amp; William Watson", title: "Eschscholzia californica i01", year: 1896, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Eschscholzia_californica_i01.jpg"), license: .publicDomain),
        "fagus_grandifolia": IllustrationCredit(creator: "François André Michaux (book author), Augustus Lucas Hillhouse (translator), Bessa (illustrator), Gabriel (engraver)", title: "NAS-106 Fagus grandifolia", year: 1819, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:NAS-106_Fagus_grandifolia.png"), license: .publicDomain),
        "ferocactus_cylindraceus": IllustrationCredit(creator: "Engelmann, George, 1809-1884; Shaw, Henry, 1800-1889; Trelease, William, 1857-1945; Gray, Asa, 1810-1888", title: "The botanical works of the late George Engelmann, collected for Henry Shaw, esq (1887) (19779666974)", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_botanical_works_of_the_late_George_Engelmann,_collected_for_Henry_Shaw,_esq_(1887)_(19779666974).jpg"), license: .publicDomain),
        "fouquieria_splendens": IllustrationCredit(creator: "M.S. del., J.N.Fitch lith.", title: "Fouquieria splendens 136-8318", year: 1910, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Fouquieria_splendens_136-8318.jpg"), license: .publicDomain),
        "frasera_speciosa": IllustrationCredit(creator: "Internet Archive Book Images", title: "Rocky Mountain flowers - an illustrated guide for plant-lovers and plant-users (1920) (14598280899)", year: 1920, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Rocky_Mountain_flowers_-_an_illustrated_guide_for_plant-lovers_and_plant-users_(1920)_(14598280899).jpg"), license: .publicDomain),
        "gaultheria_shallon": IllustrationCredit(creator: "William Hooker (1779—1832)", title: "Pursh tab. 12 Gaultheria Shallon", year: 1813, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Pursh_tab._12_Gaultheria_Shallon.jpg"), license: .publicDomain),
        "geranium_robertianum": IllustrationCredit(creator: "Georgius Jacobus Johannes van Os", title: "Dutch: Stinkende Ojevaarsbek Plate 0048, Flora Batava (KB), volume 1title QS:P1476,nl:\"Stinkende Ojevaarsbek \"label QS:L", year: 2023, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Geranium_robertianum_-_Pl0048_-_FloraBatava-KB-v01.jpg"), license: .publicDomain),
        "glechoma_hederacea": IllustrationCredit(creator: "Unknown", title: "Illustration Glechoma hederacea0", year: 2004, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Illustration_Glechoma_hederacea0.jpg"), license: .publicDomain),
        "heteromeles_arbutifolia": IllustrationCredit(creator: "Unknown", title: "Christmas berry heteromeles arbutifolia 10 feet high", year: 1911, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Christmas_berry_heteromeles_arbutifolia_10_feet_high.jpg"), license: .publicDomain),
        "hibiscus_tiliaceus": IllustrationCredit(creator: "Francisco Manuel Blanco (O.S.A.)", title: "Hibiscus tiliaceus Blanco2.274-cropped", year: 1880, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Hibiscus_tiliaceus_Blanco2.274-cropped.jpg"), license: .publicDomain),
        "holodiscus_discolor": IllustrationCredit(creator: "Edwards, Sydenham, 1769?-1819; Lindley, John, 1799-1865", title: "Edwards' botanical register, or, Ornamental flower-garden and shrubbery .. (1829-1847) (21171945425)", year: 1830, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Edwards%27_botanical_register,_or,_Ornamental_flower-garden_and_shrubbery_.._(1829-1847)_(21171945425).jpg"), license: .publicDomain),
        "ilex_vomitoria": IllustrationCredit(creator: "AnonymousUnknown author [illustrator not stated, no signature]", title: "The American Flora. Vol. 2, 1855 - pl. 30 Ilex vomitoria (14579131608)", year: 1855, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_American_Flora._Vol._2,_1855_-_pl._30_Ilex_vomitoria_(14579131608).jpg"), license: .publicDomain),
        "ipomopsis_aggregata": IllustrationCredit(creator: "Clements, Edith S.; Clements, Edith S.", title: "Flowers of mountain and plain (Plate 19) (8220461305)", year: 1920, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Flowers_of_mountain_and_plain_(Plate_19)_(8220461305).jpg"), license: .publicDomain),
        "juniperus_ashei": IllustrationCredit(creator: "Internet Archive Book Images", title: "Bulletin of the U.S. Department of Agriculture (1913-1923.) (20504921221)", year: 1916, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Bulletin_of_the_U.S._Department_of_Agriculture_(1913-1923.)_(20504921221).jpg"), license: .publicDomain),
        "lamium_amplexicaule": IllustrationCredit(creator: "Mentz, August, 1867-1944; Ostenfeld, C. H. (Carl Hansen), 1873-1931", title: "Billeder af nordens flora (1917) (20182955010)", year: 1917, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Billeder_af_nordens_flora_(1917)_(20182955010).jpg"), license: .publicDomain),
        "larrea_tridentata": IllustrationCredit(creator: "Frank Russell", title: "The Pima Indians - pl 9a", year: 1908, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_Pima_Indians_-_pl_9a.png"), license: .publicDomain),
        "liquidambar_styraciflua": IllustrationCredit(creator: "François André Michaux (book author), Augustus Lucas Hillhouse (translator), P.J. Redouté (illustrator), Gabriel (engraver)", title: "NAS-062-c Liquidambar styraciflua", year: 1819, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:NAS-062-c_Liquidambar_styraciflua.png"), license: .publicDomain),
        "lyonia_lucida": IllustrationCredit(creator: "Internet Archive Book Images", title: "Addisonia - colored illustrations and popular descriptions of plants (1916-(1964)) (16586686499)", year: 2015, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Addisonia_-_colored_illustrations_and_popular_descriptions_of_plants_(1916-(1964))_(16586686499).jpg"), license: .publicDomain),
        "malosma_laurina": IllustrationCredit(creator: "Unknown", title: "Sumac rhus laurina 6 feet high", year: 1911, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Sumac_rhus_laurina_6_feet_high.jpg"), license: .publicDomain),
        "melilotus_officinalis": IllustrationCredit(creator: "Unknown", title: "Dutch: Geneeskrachtige Melilotus Plate 0319, Flora Batava (KB), volume 4title QS:P1476,nl:\"Geneeskrachtige Melilotus \"la", year: 2023, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Melilotus_officinalis_-_Pl0319_-_FloraBatava-KB-v04.jpg"), license: .publicDomain),
        "miconia_crenata": IllustrationCredit(creator: "Jean-Baptiste-Christophe FUSÉE-AUBLET (1720-1778)", title: "Melastoma elegans Aublet 1775 pl 167", year: 1775, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Melastoma_elegans_Aublet_1775_pl_167.jpg"), license: .publicDomain),
        "mitchella_repens": IllustrationCredit(creator: "Barton, William P. C.", title: "A flora of North America (Table 95) (7176469633)", year: 1823, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:A_flora_of_North_America_(Table_95)_(7176469633).jpg"), license: .publicDomain),
        "momordica_charantia": IllustrationCredit(creator: "Francisco Manuel Blanco (O.S.A.)", title: "Momordica charantia Blanco2.357", year: 1880, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Momordica_charantia_Blanco2.357.png"), license: .publicDomain),
        "morinda_citrifolia": IllustrationCredit(creator: "Mrs. Frances Sinclair", title: "Indigenous Flowers of the Hawaiian Islands, Plate 40", year: 1885, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Indigenous_Flowers_of_the_Hawaiian_Islands,_Plate_40.jpg"), license: .publicDomain),
        "neltuma_glandulosa": IllustrationCredit(creator: "Fremont, John Charles 1813-1890 ; United States Army. Corps of Engineers", title: "Report of the exploring expedition to the Rocky Mountains in the year 1842, and to Oregon and north California in the ye", year: 1845, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Report_of_the_exploring_expedition_to_the_Rocky_Mountains_in_the_year_1842,_and_to_Oregon_and_north_California_in_the_years_1843-44_(1845)_(14760702766).jpg"), license: .publicDomain),
        "oenothera_speciosa": IllustrationCredit(creator: "Unknown", title: "Oenothera speciosa 1832J et Flore desJardins", year: 2018, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Oenothera_speciosa_1832J_et_Flore_desJardins.jpg"), license: .publicDomain),
        "onoclea_sensibilis": IllustrationCredit(creator: "Una Leonora Forster", title: "Onoclea Sensibilis Una Leonora Foster", year: 1917, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Onoclea_Sensibilis_Una_Leonora_Foster.jpg"), license: .publicDomain),
        "opuntia_basilaris": IllustrationCredit(creator: "Margaret Neilson Armstrong", title: "Opuntia Basilaris", year: 1912, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Opuntia_Basilaris_MET_DP808336.jpg"), license: .cc0),
        "opuntia_polyacantha": IllustrationCredit(creator: "Engelmann, George, 1809-1884; Shaw, Henry, 1800-1889; Trelease, William, 1857-1945; Gray, Asa, 1810-1888", title: "The botanical works of the late George Engelmann, collected for Henry Shaw, esq (1887) (20402520795)", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_botanical_works_of_the_late_George_Engelmann,_collected_for_Henry_Shaw,_esq_(1887)_(20402520795).jpg"), license: .publicDomain),
        "oxalis_pes-caprae": IllustrationCredit(creator: "Giovanni Antonio Bottione", title: "Oxalis-pes-caprae-Iconographia-Taurinensis", year: 1800, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Oxalis-pes-caprae-Iconographia-Taurinensis.jpg"), license: .publicDomain),
        "parkinsonia_microphylla": IllustrationCredit(creator: "Sargent, Charles Sprague, 1841-1927, author; Faxon, Charles Edward, 1846-1918, artist; Houghton, Mifflin and Company, publisher", title: "Silva of North America. Volume III, Anacardiaceæ - leguminosæ, The", year: 1893, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Silva_of_North_America._Volume_III,_Anacardiace%C3%A6_-_leguminos%C3%A6,_The_-_DPLA_-_0218f5acda05411627a5166b2477e083_(page_131).jpg"), license: .publicDomain),
        "pediocactus_simpsonii": IllustrationCredit(creator: "Engelmann, George, 1809-1884; Shaw, Henry, 1800-1889; Trelease, William, 1857-1945; Gray, Asa, 1810-1888", title: "The botanical works of the late George Engelmann, collected for Henry Shaw, esq (1887) (19781628663)", year: 1887, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_botanical_works_of_the_late_George_Engelmann,_collected_for_Henry_Shaw,_esq_(1887)_(19781628663).jpg"), license: .publicDomain),
        "phytolacca_americana": IllustrationCredit(creator: "Internet Archive Book Images", title: "American medical botany, being a collection of the native medicinal plants of the United States, containing their botani", year: 1817, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:American_medical_botany,_being_a_collection_of_the_native_medicinal_plants_of_the_United_States,_containing_their_botanical_history_and_chemical_analysis,_and_properties_and_uses_in_medicine,_diet_and_(17968862030).jpg"), license: .publicDomain),
        "pinus_ponderosa": IllustrationCredit(creator: "USDA-NRCS PLANTS Database / Britton, N.L., and A. Brown. 1913. Illustrated flora of the northern states and Canada. Vol. 1: 57.", title: "Pinus ponderosa drawing", year: 1913, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Pinus_ponderosa_drawing.png"), license: .publicDomain),
        "pinus_scopulorum": IllustrationCredit(creator: "Nathaniel Lord Britton &amp; Addison Brown", title: "BB-0134 Pinus scopulorum", year: 1913, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:BB-0134_Pinus_scopulorum.png"), license: .publicDomain),
        "pinus_strobus": IllustrationCredit(creator: "Internet Archive Book Images", title: "The white pine (Pinus strobus Linnaeus) (1899) (14764462405)", year: 1899, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_white_pine_(Pinus_strobus_Linnaeus)_(1899)_(14764462405).jpg"), license: .publicDomain),
        "polystichum_acrostichoides": IllustrationCredit(creator: "unknown artist; the “Fern” article is written by John Merle Coulter and Gilbert Van Ingen; Julius Bien &amp; Co. Lith. N. Y.", title: "NIE 1905 Fern", year: 1905, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:NIE_1905_Fern.jpg"), license: .publicDomain),
        "populus_tremuloides": IllustrationCredit(creator: "François André Michaux (book author), Augustus Lucas Hillhouse (translator), Pancrace Bessa (illustrator), Gabriel (engraver)", title: "NAS-099 Populus tremuloides & grandidentata", year: 1819, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:NAS-099_Populus_tremuloides_%26_grandidentata.png"), license: .publicDomain),
        "prunella_vulgaris": IllustrationCredit(creator: "File:Illustration Prunella vulgaris0.jpg: PLEASE COMPLETE AUTHOR INFORMATION derivative work: Kenraiz", title: "Illustration Prunella vulgaris0 cleaned", year: 2023, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Illustration_Prunella_vulgaris0_cleaned.jpg"), license: .publicDomain),
        "pseudotsuga_menziesii": IllustrationCredit(creator: "Mary Vaux Walcott", title: "Pseudotsuga menziesii, by Mary Vaux Walcott", sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Pseudotsuga_menziesii,_by_Mary_Vaux_Walcott.jpg"), license: .publicDomain),
        "quercus_agrifolia": IllustrationCredit(creator: "Internet Archive Book Images", title: "Forest trees of the Pacific slope (1908) (14780638925)", year: 1908, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Forest_trees_of_the_Pacific_slope_(1908)_(14780638925).jpg"), license: .publicDomain),
        "quercus_gambelii": IllustrationCredit(creator: "The British Library", title: "Image taken from page 327 of 'Report of an expedition down the Zuni and Colorado Rivers by Captain L. Sitgreaves (110424", year: 2013, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Image_taken_from_page_327_of_%27Report_of_an_expedition_down_the_Zuni_and_Colorado_Rivers_by_Captain_L._Sitgreaves_(11042471045).jpg"), license: .publicDomain),
        "rhus_copallina": IllustrationCredit(creator: "Sargent, Charles Sprague, 1841-1927, author; Faxon, Charles Edward, 1846-1918, artist; Houghton, Mifflin and Company, publisher", title: "Silva of North America. Volume III, Anacardiaceæ - leguminosæ, The", year: 1893, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Silva_of_North_America._Volume_III,_Anacardiace%C3%A6_-_leguminos%C3%A6,_The_-_DPLA_-_0218f5acda05411627a5166b2477e083_(page_36).jpg"), license: .publicDomain),
        "rhus_integrifolia": IllustrationCredit(creator: "Internet Archive Book Images", title: "Chaparral - studies in the dwarf forests, or elfin-wood, of southern California (1911) (20596498991)", year: 1911, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Chaparral_-_studies_in_the_dwarf_forests,_or_elfin-wood,_of_southern_California_(1911)_(20596498991).jpg"), license: .publicDomain),
        "rosa_multiflora": IllustrationCredit(creator: "Pierre-Joseph Redouté", title: "Rosa multiflora carnea 001", year: 1817, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Rosa_multiflora_carnea_001.JPG"), license: .publicDomain),
        "rubus_spectabilis": IllustrationCredit(creator: "Frederick Traugott Pursh", title: "Flora Americae Septentrionalis - or, A systematic arrangement and description of the plants of North America. Containing", year: 1816, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Flora_Americae_Septentrionalis_-_or,_A_systematic_arrangement_and_description_of_the_plants_of_North_America._Containing,_besides_what_have_been_described_by_preceding_authors,_many_new_and_rare_(14577557157).jpg"), license: .publicDomain),
        "rubus_ursinus": IllustrationCredit(creator: "Hooker, William Jackson", title: "Flora boreali-americana, or, the botany of the northern parts of British America (Tab. LIX) (8188329662)", year: 1840, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Flora_boreali-americana,_or,_the_botany_of_the_northern_parts_of_British_America_(Tab._LIX)_(8188329662).jpg"), license: .publicDomain),
        "sabal_palmetto": IllustrationCredit(creator: "Adèle Riché", title: "NAS-101 Sabal palmetto", year: 1819, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:NAS-101_Sabal_palmetto.png"), license: .publicDomain),
        "sambucus_canadensis": IllustrationCredit(creator: "Internet Archive Book Images", title: "Cyclopedia of American horticulture, comprising suggestions for cultivation of horticultural plants, descriptions of the", year: 1906, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Cyclopedia_of_American_horticulture,_comprising_suggestions_for_cultivation_of_horticultural_plants,_descriptions_of_the_species_of_fruits,_vegetables,_flowers_and_ornamental_plants_sold_in_the_United_(14760541531).jpg"), license: .publicDomain),
        "sambucus_racemosa": IllustrationCredit(creator: "Internet Archive Book Images", title: "The American midland naturalist (1909) (18158121001)", year: 1909, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_American_midland_naturalist_(1909)_(18158121001).jpg"), license: .publicDomain),
        "scaevola_taccada": IllustrationCredit(creator: "Francisco Manuel Blanco (O.S.A.)", title: "Scaevola taccada Blanco1.210-cropped", year: 1880, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Scaevola_taccada_Blanco1.210-cropped.jpg"), license: .publicDomain),
        "serenoa_repens": IllustrationCredit(creator: "Lounsberry, Alice.; Rowan, Marian Ellis Ryan", title: "Southern wild flowers and trees (Page 29, Plate X) BHL23630201", year: 1901, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Southern_wild_flowers_and_trees_(Page_29,_Plate_X)_BHL23630201.jpg"), license: .publicDomain),
        "solanum_dulcamara": IllustrationCredit(creator: "Internet Archive Book Images", title: "The natural history of plants, their forms, growth, reproduction, and distribution; (1902) (14760550156)", year: 1902, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_natural_history_of_plants,_their_forms,_growth,_reproduction,_and_distribution;_(1902)_(14760550156).jpg"), license: .publicDomain),
        "sphaeralcea_coccinea": IllustrationCredit(creator: "Nathaniel Lord Britton (1859-1934), and A. Brown", title: "Sphaeralcea coccinea-linedrawing", year: 1913, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Sphaeralcea_coccinea-linedrawing.png"), license: .publicDomain),
        "symphoricarpos_albus": IllustrationCredit(creator: "Barton, William P. C.", title: "A flora of North America (Table 19) (7351973590)", year: 1821, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:A_flora_of_North_America_(Table_19)_(7351973590).jpg"), license: .publicDomain),
        "symplocarpus_foetidus": IllustrationCredit(creator: "AnonymousUnknown author [illustrator not stated, no signature]", title: "The American Flora. Vol. 3, 1855 - pl. 19 Symplocarpus sp. (10172257375)", year: 1855, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_American_Flora._Vol._3,_1855_-_pl._19_Symplocarpus_sp._(10172257375).jpg"), license: .publicDomain),
        "thespesia_populnea": IllustrationCredit(creator: "Francisco Manuel Blanco (O.S.A.)", title: "Thespesia populnea Blanco2.247-original", year: 1880, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Thespesia_populnea_Blanco2.247-original.png"), license: .publicDomain),
        "thuja_plicata": IllustrationCredit(creator: "Mary Vaux Walcott", title: "Thuja plicata-3, by Mary Vaux Walcott", sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Thuja_plicata-3,_by_Mary_Vaux_Walcott.jpg"), license: .publicDomain),
        "toxicodendron_radicans": IllustrationCredit(creator: "Internet Archive Book Images", title: "American medical botany- being a collection of the native medicinal plants of the United States, containing their botani", year: 1817, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:American_medical_botany-_being_a_collection_of_the_native_medicinal_plants_of_the_United_States,_containing_their_botanical_history_and_chemical_analysis,_and_properties_and_uses_in_medicine,_diet_and_(14740707516).jpg"), license: .publicDomain),
        "umbellularia_californica": IllustrationCredit(creator: "Michaux, François André, 1770-1855. cn; Nuttall, Thomas, 1786-1859. 1n; Smith, J. Jay (John Jay), 1798-1881", title: "The North American sylva; or, A description of the forest trees of the United States, Canada and Nova Scotia. Considered", year: 1865, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:The_North_American_sylva;_or,_A_description_of_the_forest_trees_of_the_United_States,_Canada_and_Nova_Scotia._Considered_particularly_with_respect_to_their_use_in_the_arts_and_their_introduction_into_(14781382372).jpg"), license: .publicDomain),
        "urena_lobata": IllustrationCredit(creator: "Basu, Baman Das; Kirtikar, Kanhoba Ranchoddas", title: "Indian medicinal plants (Plate 125) (7824411394)", year: 1918, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Indian_medicinal_plants_(Plate_125)_(7824411394).jpg"), license: .publicDomain),
        "vitis_rotundifolia": IllustrationCredit(creator: "Audubon, John James, 1785-1851; Havell, Robert, 1793-1878", title: "Summer red bird Male old, 1. Young, 2. F, 3. Tanagra Æstiva. Plant vulgo. Wild muscadine. Vitis rotundifolia c.2 v.1 pla", year: 2025, sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Summer_red_bird_Male_old,_1._Young,_2._F,_3._Tanagra_%C3%86stiva._Plant_vulgo._Wild_muscadine._Vitis_rotundifolia_c.2_v.1_plate_44_-_DPLA_-_4321acd6688e874d9ae95f4c9360a6c8_(page_1).jpg"), license: .publicDomain)
    ]
}
